# Generated by Django 2.2.3 on 2019-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_auto_20190815_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
        migrations.AddField(
            model_name='messagebox',
            name='unread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
