# Generated by Django 2.2.3 on 2019-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_auto_20190816_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebox',
            name='unread',
        ),
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
