# Generated by Django 2.2.3 on 2019-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_auto_20190817_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebox',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
