# Generated by Django 2.2.3 on 2019-08-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_messagebox_last_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebox',
            name='last_time',
        ),
    ]
