# Generated by Django 2.2.3 on 2019-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
