# Generated by Django 3.0.2 on 2020-01-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0002_auto_20200124_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
